# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c423a715e1617361fb43f0d133da4ce01a047f22e8ae96be5c54b059202a45a3dd918ab25bbf803ff3a6753322050dd7497713d4f53db825541b3099f94b375c

test:
  secret_key_base: 4a339263686577da2fd80ed463e4a61938d793a29e51d26dfa057f5fb3a7c3cacaf0f05bd56d3da0e930ef00e03bd3b8cb630435cdd26ff8c49db5b5c9d24e16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
